// Generated by gencpp from file arm/angles.msg
// DO NOT EDIT!


#ifndef ARM_MESSAGE_ANGLES_H
#define ARM_MESSAGE_ANGLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm
{
template <class ContainerAllocator>
struct angles_
{
  typedef angles_<ContainerAllocator> Type;

  angles_()
    : shoulder(0)
    , elbow(0)
    , wrist(0)  {
    }
  angles_(const ContainerAllocator& _alloc)
    : shoulder(0)
    , elbow(0)
    , wrist(0)  {
  (void)_alloc;
    }



   typedef uint16_t _shoulder_type;
  _shoulder_type shoulder;

   typedef uint16_t _elbow_type;
  _elbow_type elbow;

   typedef uint16_t _wrist_type;
  _wrist_type wrist;





  typedef boost::shared_ptr< ::arm::angles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm::angles_<ContainerAllocator> const> ConstPtr;

}; // struct angles_

typedef ::arm::angles_<std::allocator<void> > angles;

typedef boost::shared_ptr< ::arm::angles > anglesPtr;
typedef boost::shared_ptr< ::arm::angles const> anglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm::angles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm::angles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'arm': ['/home/johnnyname/arm_ws/src/arm/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arm::angles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm::angles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm::angles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm::angles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm::angles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm::angles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm::angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8960ce5da37f48308cf296b103d3ad7f";
  }

  static const char* value(const ::arm::angles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8960ce5da37f4830ULL;
  static const uint64_t static_value2 = 0x8cf296b103d3ad7fULL;
};

template<class ContainerAllocator>
struct DataType< ::arm::angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm/angles";
  }

  static const char* value(const ::arm::angles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm::angles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 shoulder\n"
"uint16 elbow\n"
"uint16 wrist\n"
;
  }

  static const char* value(const ::arm::angles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm::angles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shoulder);
      stream.next(m.elbow);
      stream.next(m.wrist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct angles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm::angles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm::angles_<ContainerAllocator>& v)
  {
    s << indent << "shoulder: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.shoulder);
    s << indent << "elbow: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.elbow);
    s << indent << "wrist: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.wrist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_MESSAGE_ANGLES_H
